<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="4" failed="2" total="25" passed="19">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="153929" started-at="2020-04-05T05:44:27Z" finished-at="2020-04-05T05:47:01Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="153929" started-at="2020-04-05T05:44:27Z" finished-at="2020-04-05T05:47:01Z">
      <class name="com.tests.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.LoginPageTest@1784306]" name="setUp" is-config="true" duration-ms="15208" started-at="2020-04-05T11:14:55Z" finished-at="2020-04-05T11:15:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="SKIP" signature="verifyLoginPageTitleTest()[pri:0, instance:com.tests.LoginPageTest@1784306]" name="verifyLoginPageTitleTest" duration-ms="1563" started-at="2020-04-05T11:15:10Z" finished-at="2020-04-05T11:15:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login - My Store.] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login - My Store.] but found [Login - My Store]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tests.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="SKIP" signature="verifyLoginPageTitleTest()[pri:0, instance:com.tests.LoginPageTest@1784306]" name="verifyLoginPageTitleTest" duration-ms="2254" started-at="2020-04-05T11:15:12Z" finished-at="2020-04-05T11:15:14Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login - My Store.] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login - My Store.] but found [Login - My Store]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tests.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="FAIL" signature="verifyLoginPageTitleTest()[pri:0, instance:com.tests.LoginPageTest@1784306]" name="verifyLoginPageTitleTest" duration-ms="1926" started-at="2020-04-05T11:15:14Z" finished-at="2020-04-05T11:15:16Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Login - My Store.] but found [Login - My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Login - My Store.] but found [Login - My Store]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at com.tests.LoginPageTest.verifyLoginPageTitleTest(LoginPageTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.tests.LoginPageTest@1784306]" name="loginTest" duration-ms="2740" started-at="2020-04-05T11:15:17Z" finished-at="2020-04-05T11:15:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="verifyLoginTest()[pri:2, instance:com.tests.LoginPageTest@1784306]" name="verifyLoginTest" duration-ms="129" started-at="2020-04-05T11:15:19Z" finished-at="2020-04-05T11:15:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginTest -->
        <test-method status="PASS" signature="verifyAccountPageTitleTest()[pri:3, instance:com.tests.LoginPageTest@1784306]" name="verifyAccountPageTitleTest" duration-ms="18" started-at="2020-04-05T11:15:20Z" finished-at="2020-04-05T11:15:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountPageTitleTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.LoginPageTest@1784306]" name="tearDown" is-config="true" duration-ms="898" started-at="2020-04-05T11:15:20Z" finished-at="2020-04-05T11:15:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.LoginPageTest -->
      <class name="com.tests.CreateAccountPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.CreateAccountPageTest@185d8b6]" name="setUp" is-config="true" duration-ms="15610" started-at="2020-04-05T11:14:27Z" finished-at="2020-04-05T11:14:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginPageTitleTest()[pri:0, instance:com.tests.CreateAccountPageTest@185d8b6]" name="verifyLoginPageTitleTest" duration-ms="2463" started-at="2020-04-05T11:14:42Z" finished-at="2020-04-05T11:14:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginPageTitleTest -->
        <test-method status="PASS" signature="createAccountTest()[pri:1, instance:com.tests.CreateAccountPageTest@185d8b6]" name="createAccountTest" duration-ms="8172" started-at="2020-04-05T11:14:45Z" finished-at="2020-04-05T11:14:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
        <test-method status="SKIP" signature="verifyAccountTest()[pri:2, instance:com.tests.CreateAccountPageTest@185d8b6]" name="verifyAccountTest" duration-ms="197" started-at="2020-04-05T11:14:53Z" finished-at="2020-04-05T11:14:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user not matched expected [SidhiPatel] but found [Sidhi Patel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user not matched expected [SidhiPatel] but found [Sidhi Patel]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.tests.CreateAccountPageTest.verifyAccountTest(CreateAccountPageTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:823)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountTest -->
        <test-method status="SKIP" signature="verifyAccountTest()[pri:2, instance:com.tests.CreateAccountPageTest@185d8b6]" name="verifyAccountTest" duration-ms="126" started-at="2020-04-05T11:14:53Z" finished-at="2020-04-05T11:14:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user not matched expected [SidhiPatel] but found [Sidhi Patel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user not matched expected [SidhiPatel] but found [Sidhi Patel]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.tests.CreateAccountPageTest.verifyAccountTest(CreateAccountPageTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountTest -->
        <test-method status="FAIL" signature="verifyAccountTest()[pri:2, instance:com.tests.CreateAccountPageTest@185d8b6]" name="verifyAccountTest" duration-ms="125" started-at="2020-04-05T11:14:53Z" finished-at="2020-04-05T11:14:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[user not matched expected [SidhiPatel] but found [Sidhi Patel]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: user not matched expected [SidhiPatel] but found [Sidhi Patel]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.tests.CreateAccountPageTest.verifyAccountTest(CreateAccountPageTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:970)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1149)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1225)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1150)
	at org.testng.TestNG.runSuites(TestNG.java:1075)
	at org.testng.TestNG.run(TestNG.java:1047)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAccountTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.CreateAccountPageTest@185d8b6]" name="tearDown" is-config="true" duration-ms="945" started-at="2020-04-05T11:14:54Z" finished-at="2020-04-05T11:14:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.CreateAccountPageTest -->
      <class name="com.tests.CheckoutProcessPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="setUp" is-config="true" duration-ms="21097" started-at="2020-04-05T11:16:06Z" finished-at="2020-04-05T11:16:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyaddProductToCartTest()[pri:0, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyaddProductToCartTest" duration-ms="13351" started-at="2020-04-05T11:16:27Z" finished-at="2020-04-05T11:16:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyaddProductToCartTest -->
        <test-method status="PASS" signature="navigateToCheckoutPageTest()[pri:1, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="navigateToCheckoutPageTest" duration-ms="2667" started-at="2020-04-05T11:16:40Z" finished-at="2020-04-05T11:16:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToCheckoutPageTest -->
        <test-method status="PASS" signature="verifyOrderPageTitleTest()[pri:2, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyOrderPageTitleTest" duration-ms="30" started-at="2020-04-05T11:16:43Z" finished-at="2020-04-05T11:16:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderPageTitleTest -->
        <test-method status="PASS" signature="verifySummaryTab()[pri:3, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifySummaryTab" duration-ms="415" started-at="2020-04-05T11:16:43Z" finished-at="2020-04-05T11:16:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySummaryTab -->
        <test-method status="PASS" signature="checkTermsOfService()[pri:4, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="checkTermsOfService" duration-ms="6067" started-at="2020-04-05T11:16:43Z" finished-at="2020-04-05T11:16:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkTermsOfService -->
        <test-method status="PASS" signature="verifyPaymentTab()[pri:5, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyPaymentTab" duration-ms="230" started-at="2020-04-05T11:16:49Z" finished-at="2020-04-05T11:16:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPaymentTab -->
        <test-method status="PASS" signature="paymentProcessTest()[pri:6, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="paymentProcessTest" duration-ms="5898" started-at="2020-04-05T11:16:49Z" finished-at="2020-04-05T11:16:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- paymentProcessTest -->
        <test-method status="PASS" signature="verifyOrderConfirmationPageTitleTest()[pri:7, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyOrderConfirmationPageTitleTest" duration-ms="35" started-at="2020-04-05T11:16:55Z" finished-at="2020-04-05T11:16:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyOrderConfirmationPageTitleTest -->
        <test-method status="PASS" signature="verifyorderConfirmationMsgTest()[pri:8, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyorderConfirmationMsgTest" duration-ms="85" started-at="2020-04-05T11:16:55Z" finished-at="2020-04-05T11:16:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyorderConfirmationMsgTest -->
        <test-method status="PASS" signature="verifyAmountOrderHistoryTest()[pri:9, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="verifyAmountOrderHistoryTest" duration-ms="4319" started-at="2020-04-05T11:16:55Z" finished-at="2020-04-05T11:17:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAmountOrderHistoryTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.CheckoutProcessPageTest@10366b4]" name="tearDown" is-config="true" duration-ms="827" started-at="2020-04-05T11:17:00Z" finished-at="2020-04-05T11:17:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.CheckoutProcessPageTest -->
      <class name="com.tests.AddToCartPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.tests.AddToCartPageTest@15eadca]" name="setUp" is-config="true" duration-ms="26202" started-at="2020-04-05T11:15:21Z" finished-at="2020-04-05T11:15:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyLoginTest()[pri:0, instance:com.tests.AddToCartPageTest@15eadca]" name="verifyLoginTest" duration-ms="139" started-at="2020-04-05T11:15:47Z" finished-at="2020-04-05T11:15:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLoginTest -->
        <test-method status="PASS" signature="verifyWomenStorePageTitle()[pri:1, instance:com.tests.AddToCartPageTest@15eadca]" name="verifyWomenStorePageTitle" duration-ms="5885" started-at="2020-04-05T11:15:47Z" finished-at="2020-04-05T11:15:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWomenStorePageTitle -->
        <test-method status="PASS" signature="verifyaddProductToCartTest()[pri:2, instance:com.tests.AddToCartPageTest@15eadca]" name="verifyaddProductToCartTest" duration-ms="9750" started-at="2020-04-05T11:15:53Z" finished-at="2020-04-05T11:16:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyaddProductToCartTest -->
        <test-method status="PASS" signature="navigateToCheckoutPageTest()[pri:3, instance:com.tests.AddToCartPageTest@15eadca]" name="navigateToCheckoutPageTest" duration-ms="2011" started-at="2020-04-05T11:16:03Z" finished-at="2020-04-05T11:16:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateToCheckoutPageTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.tests.AddToCartPageTest@15eadca]" name="tearDown" is-config="true" duration-ms="1016" started-at="2020-04-05T11:16:05Z" finished-at="2020-04-05T11:16:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.tests.AddToCartPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
